services:
  # Backend - FastAPI
  - type: web
    name: endereco-alga-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    autoDeploy: true

  # Frontend - React (Static Site)
  - type: web
    name: endereco-alga-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    envVars:
      - key: VITE_API_URL
        # IMPORTANTE: Após criar os serviços, atualize esta URL com a URL real do backend
        # Exemplo: https://endereco-alga-backend.onrender.com
        value: https://endereco-alga-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

databases: []
